task: segmentation
device: cuda
dataset:
  name: ShapeNetPart
  dataset_dir: ~/datasets
  num_points: 2048
  use_normals: False
model:
  type: dgcnn
  name: dgcnn_seg
  dgcnn:
    k: 20
    edge_dims: [64, 64, 64, 128]
    emb_dims: 1024
    dropout: 0.5
train:
  batch_size: 12
  optimizer: adam
  base_lr: 0.001
  weight_decay: 1e-4
  output_dir: experiments/point_cloud/shapenetpart/dgcnn_seg
  log_period: 10
  checkpoint_period: 10
  dataloader:
    num_workers: 2
    drop_last: True
    pin_memory: False
validation:
  batch_size: 12
scheduler:
  epochs: 200
  type: cosine
test:
  batch_size: 12
