task: segmentation
device: cuda
dataset:
  name: ShapeNetPart
  dataset_dir: ~/datasets
  num_points: 2048
  use_normals: False
model:
  type: pointvoxel
  name: pointvoxel_seg
  pointvoxel:
    block_channels: [64, 128, 256]
    voxel_resolution: 16
    decoder_dim: 128
    dropout: 0.3
train:
  batch_size: 12
  optimizer: adamw
  base_lr: 0.0005
  weight_decay: 1e-4
  output_dir: experiments/point_cloud/shapenetpart/pointvoxel_seg
  log_period: 10
  checkpoint_period: 10
  dataloader:
    num_workers: 2
    drop_last: True
    pin_memory: False
validation:
  batch_size: 12
scheduler:
  epochs: 250
  type: cosine
test:
  batch_size: 12
