model:
  type: imagenet
  name: edgevit
  init_mode: transformer
  edgevit:
    patch_size: 16
    emb_dim: 512
    mlp_dim: 2048
    num_heads: 8
    num_layers: 14
    dropout: 0.0
    attention_dropout: 0.0
    drop_path_rate: 0.1
    classifier: token
    representation_size: 0
    qkv_bias: true
    pretrained: false
    pretrained_path: ''
    pretrained_source: checkpoint
    strict_pretrained_load: false
    reset_classifier: true
    interpolate_position_embedding: true
device: cuda
train:
  resume: false
  seed: 0
  precision: O0
  batch_size: 256
  subdivision: 1
  optimizer: adamw
  base_lr: 0.001
  momentum: 0.9
  nesterov: true
  weight_decay: 0.05
  no_weight_decay_on_bn: true
  output_dir: experiments/imagenet/edgevit_base/exp00
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: true
  distributed: false
  dataloader:
    num_workers: 8
    drop_last: true
    pin_memory: true
validation:
  batch_size: 256
  dataloader:
    num_workers: 8
    drop_last: false
    pin_memory: true
scheduler:
  epochs: 300
  type: cosine
tensorboard:
  train_images: false
  val_images: false
  model_params: false
