model:
  type: imagenet
  name: pyramidnet
  init_mode: kaiming_fan_out
  pyramidnet:
    n_blocks:
    - 3
    - 24
    - 36
    - 3
    initial_channels: 64
    block_type: bottleneck
    alpha: 300
device: cuda
train:
  resume: false
  seed: 0
  precision: O0
  batch_size: 128
  subdivision: 1
  optimizer: sgd
  base_lr: 0.05
  momentum: 0.9
  nesterov: true
  weight_decay: 1e-4
  output_dir: experiments/imagenet/pyramidnet200/exp00
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: true
  distributed: false
  dataloader:
    num_workers: 8
    drop_last: true
    pin_memory: true
validation:
  batch_size: 256
  dataloader:
    num_workers: 8
    drop_last: false
    pin_memory: true
scheduler:
  epochs: 120
  type: multistep
  milestones:
  - 60
  - 90
  - 105
  lr_decay: 0.1
tensorboard:
  train_images: false
  val_images: false
  model_params: false
